name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Build
      run: |
        env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o linux-amd64/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o linux-386/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build -o linux-arm-5/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -o linux-arm-6/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o linux-arm-7/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o linux-arm64/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o darwin-amd64/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o darwin-arm64/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o windows-amd64/chnroutes-webui.exe -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o windows-386/chnroutes-webui.exe -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -o freebsd-amd64/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=freebsd GOARCH=386 go build -o freebsd-386/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 go build -o openbsd-amd64/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=openbsd GOARCH=386 go build -o openbsd-386/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 go build -o netbsd-amd64/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=netbsd GOARCH=386 go build -o netbsd-386/chnroutes-webui -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 go build -o dragonfly-amd64/chnroutes-webui -ldflags="-s -w" .
        env GOPATH=$PWD/gopath go get -u github.com/missdeer/cicdutil
      
    - name: Upload artifact chnroutes-webui-linux-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-linux-amd64
        # Directory containing files to upload
        path: linux-amd64

    - name: Upload artifact chnroutes-webui-linux-386
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-linux-386
        # Directory containing files to upload
        path: linux-386

    - name: Upload artifact chnroutes-webui-linux-arm-5
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-linux-arm-5
        # Directory containing files to upload
        path: linux-arm-5

    - name: Upload artifact chnroutes-webui-linux-arm-6
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-linux-arm-6
        # Directory containing files to upload
        path: linux-arm-6

    - name: Upload artifact chnroutes-webui-linux-arm-7
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-linux-arm-7
        # Directory containing files to upload
        path: linux-arm-7

    - name: Upload artifact chnroutes-webui-linux-arm64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-linux-arm64
        # Directory containing files to upload
        path: linux-arm64

    - name: Upload artifact chnroutes-webui-darwin-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-darwin-amd64
        # Directory containing files to upload
        path: darwin-amd64

    - name: Upload artifact chnroutes-webui-darwin-arm64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-darwin-arm64
        # Directory containing files to upload
        path: darwin-arm64

    - name: Upload artifact chnroutes-webui-dragonfly-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-dragonfly-amd64
        # Directory containing files to upload
        path: dragonfly-amd64

    - name: Upload artifact chnroutes-webui-openbsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-openbsd-amd64
        # Directory containing files to upload
        path: openbsd-amd64

    - name: Upload artifact chnroutes-webui-openbsd-386
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-openbsd-386
        # Directory containing files to upload
        path: openbsd-386

    - name: Upload artifact chnroutes-webui-netbsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-netbsd-amd64
        # Directory containing files to upload
        path: netbsd-amd64

    - name: Upload artifact chnroutes-webui-netbsd-386
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-netbsd-386
        # Directory containing files to upload
        path: netbsd-386

    - name: Upload artifact chnroutes-webui-freebsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-freebsd-amd64
        # Directory containing files to upload
        path: freebsd-amd64

    - name: Upload artifact chnroutes-webui-freebsd-386
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-freebsd-386
        # Directory containing files to upload
        path: freebsd-386

    - name: Upload artifact chnroutes-webui-windows-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-windows-amd64
        # Directory containing files to upload
        path: windows-amd64

    - name: Upload artifact chnroutes-webui-windows-386
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: chnroutes-webui-windows-386
        # Directory containing files to upload
        path: windows-386

    - name: Remove old artifacts
      run: |
        gopath/bin/cicdutil -p github -u missdeer -t ${{ secrets.GH_TOKEN }} -r chnroutes-webui -k 0 -a delete
